TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../hdl/decoder.sv
TOPLEVEL = decoder
MODULE = test_decoder

export PYTHONPATH := $(abspath ../model)

include $(shell cocotb-config --makefiles)/Makefile.sim

